defaults = dict()
defaults['remove_doubles'] = True
defaults['recalculate_normals'] = True
defaults['merge_distance'] = 0.05
defaults['triangulate'] = False
defaults['meta_group'] = True
defaults['meta_print_write'] = False
defaults['meta_step'] = False
defaults['meta_clear'] = False
defaults['meta_pause'] = False
defaults['meta_save'] = False
defaults['display_logo'] = False
defaults['shade_smooth'] = True
defaults['make_gaps'] = True
defaults['gap_scale'] = 0.997
defaults['no_studs'] = False
defaults['set_end_frame'] = False
defaults['starting_step_frame'] = 1
defaults['frames_per_step'] = 3
defaults['set_timelime_markers'] = False
defaults['smooth_type'] = "edge_split"  # "edge_split" "auto_smooth"
defaults['gap_target'] = "object"  # "mesh"
defaults['gap_scale_strategy'] = "constraint"  # "object" "constraint"
defaults['import_edges'] = False
defaults['use_freestyle_edges'] = False
defaults['grease_pencil_edges'] = False
defaults['import_scale'] = 0.02
defaults['parent_to_empty'] = True  # True False
defaults['treat_shortcut_as_model'] = True  # False TODO: parent to empty at median of group
defaults['sharpen_edges'] = True
defaults['instancing'] = False

remove_doubles = defaults['remove_doubles']
merge_distance = defaults['merge_distance']
shade_smooth = defaults['shade_smooth']
display_logo = defaults['display_logo']
make_gaps = defaults['make_gaps']
gap_scale = defaults['gap_scale']
no_studs = defaults['no_studs']
set_timelime_markers = defaults['set_timelime_markers']
meta_group = defaults['meta_group']
meta_print_write = defaults['meta_print_write']
meta_step = defaults['meta_step']
meta_clear = defaults['meta_clear']
meta_pause = defaults['meta_pause']
meta_save = defaults['meta_save']
set_end_frame = defaults['set_end_frame']
starting_step_frame = defaults['starting_step_frame']
frames_per_step = defaults['frames_per_step']
smooth_type = defaults['smooth_type']
import_edges = defaults['import_edges']
use_freestyle_edges = defaults['use_freestyle_edges']
grease_pencil_edges = defaults['grease_pencil_edges']
import_scale = defaults['import_scale']
parent_to_empty = defaults['parent_to_empty']
gap_target = defaults['gap_target']
gap_scale_strategy = defaults['gap_scale_strategy']
treat_shortcut_as_model = defaults['treat_shortcut_as_model']
recalculate_normals = defaults['recalculate_normals']
triangulate = defaults['triangulate']
sharpen_edges = defaults['sharpen_edges']
instancing = defaults['instancing']
