ldraw_path = None
ldraw_edge_key = "ldraw_edge"
ldraw_filename_key = "ldraw_filename"
ldraw_color_code_key = "ldraw_color_code"
ldraw_export_polygons_key = "ldraw_export_polygons"
ldraw_export_precision_key = "ldraw_export_precision"

meta_group = True
meta_print_write = False
meta_step = False
meta_clear = False
meta_pause = False
meta_save = False
display_logo = False
chosen_logo = None
use_alt_colors = True
remove_doubles = True
merge_distance = 0.05
shade_smooth = True
make_gaps = True
gap_scale = 0.997
debug_text = False
no_studs = False
bevel_edges = False
set_end_frame = False
starting_step_frame = 1
frames_per_step = 3
curved_walls = False
add_subsurface = False
resolution = "Standard"
set_timelime_markers = "Standard"
prefer_unofficial = False
smooth_type = "edge_split"  # "auto_smooth"
gap_target = "object"  # "mesh"
gap_scale_strategy = "constraint"  # "object"
import_edges = False
grease_pencil_edges = False
import_scale = 0.02
camera_fov = 30.0
camera_near = 1.0
camera_far = 10000.0
parent_to_empty = True
