ldraw_path = ""
meta_group = True
meta_print_write = False
meta_step = False
meta_clear = False
meta_pause = False
meta_save = False
display_logo = False
chosen_logo = None
use_alt_colors = True
remove_doubles = True
remove_doubles_strategy = "bmesh_ops"
merge_distance = 0.05
shade_smooth = True
make_gaps = True
gap_scale = 0.997
debug_text = False
no_studs = False
bevel_edges = False
set_end_frame = False
starting_step_frame = 1
frames_per_step = 3
add_subsurface = False
resolution = "Standard"
set_timelime_markers = "Standard"
prefer_unofficial = False
smooth_type = "edge_split"  # "auto_smooth"
gap_target = "object"  # "mesh"
gap_scale_strategy = "constraint"  # "object"
import_edges = False
grease_pencil_edges = False
import_scale = 0.02
camera_fov = 30.0
camera_near = 1.0
camera_far = 10000.0
parent_to_empty = True
all_materials = True
selection_only = True
export_precision = 2
recalculate_normals = True
triangulate = False
ngon_handling = "triangulate"

# options without a ui
instancing = False
treat_shortcut_as_model = False
do_texmaps = False
use_glass = True
slope_texture_strength = 0.6
