ldraw_filename_key = "ldraw_filename"
ldraw_color_code_key = "ldraw_color_code"
ldraw_color_name_key = "ldraw_color_name"
ldraw_export_polygons_key = "ldraw_export_polygons"
ldraw_export_precision_key = "ldraw_export_precision"
